import { prisma } from "@/lib/prisma";
import { requireUser, requireProjectAccess } from "@/lib/dal";
import { handleError } from "@/lib/api";

/* ───────────────── Translation dictionary ───────────────── */

const exportDict: Record<string, { en: string; he: string }> = {
  budget: { en: "Budget", he: "תקציב" },
  totalCost: { en: "Total Cost", he: "עלות כוללת" },
  paid: { en: "Paid", he: "שולם" },
  remaining: { en: "Remaining", he: "נותר" },
  budgetLeft: { en: "Budget Left", he: "תקציב שנותר" },
  task: { en: "Task", he: "משימה" },
  parent: { en: "Parent", he: "משימת אב" },
  category: { en: "Category", he: "קטגוריה" },
  vendor: { en: "Vendor", he: "ספק" },
  rooms: { en: "Rooms", he: "חדרים" },
  status: { en: "Status", he: "סטטוס" },
  cost: { en: "Cost", he: "עלות" },
  left: { en: "Left", he: "נותר" },
  payments: { en: "Payments", he: "תשלומים" },
  milestone: { en: "Milestone", he: "תשלום" },
  amount: { en: "Amount", he: "סכום" },
  dueDate: { en: "Due Date", he: "תאריך יעד" },
  paidDate: { en: "Paid Date", he: "תאריך תשלום" },
  issues: { en: "Issues", he: "תקלות" },
  inProgress: { en: "In Progress", he: "בתהליך" },
  completed: { en: "Completed", he: "הושלם" },
  pending: { en: "Pending", he: "ממתין" },
  financialSummary: { en: "Financial Summary", he: "סיכום פיננסי" },
  topTasks: { en: "Top Tasks", he: "משימות מובילות" },
  generatedBy: { en: "Generated by Reno Tracker", he: "נוצר על ידי Reno Tracker" },
  projectReport: { en: "Project Report", he: "דוח פרויקט" },
  generated: { en: "Generated", he: "נוצר" },
  onTrack: { en: "on track", he: "במסלול" },
  overBudget: { en: "over budget", he: "חריגה" },
};

type Lang = "en" | "he";

function createTranslator(lang: Lang) {
  return (key: string) => exportDict[key]?.[lang] || key;
}

/* ───────────────── Helpers ───────────────── */

function fmtILS(n: number) {
  return new Intl.NumberFormat("he-IL", { style: "currency", currency: "ILS", maximumFractionDigits: 0 }).format(n);
}

function fmtDate(d: Date | string, lang: Lang) {
  const locale = lang === "he" ? "he-IL" : "en-IL";
  return new Date(d).toLocaleDateString(locale);
}

/* ───────────────── GET handler ───────────────── */

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { userId } = await requireUser();
    const { id } = await params;
    await requireProjectAccess(userId, id);

    const { searchParams } = new URL(request.url);
    const format = searchParams.get("format") || "csv";
    const lang: Lang = searchParams.get("lang") === "he" ? "he" : "en";
    const et = createTranslator(lang);

    const project = await prisma.project.findUnique({ where: { id } });
    if (!project) return new Response("Not found", { status: 404 });

    const nodes = await prisma.projectNode.findMany({
      where: { projectId: id },
      include: {
        vendor: { select: { name: true } },
        category: { select: { name: true } },
        milestones: { select: { label: true, amount: true, status: true, dueDate: true, paidDate: true } },
        rooms: { include: { room: { select: { name: true } } } },
        parent: { select: { name: true } },
      },
      orderBy: { sortOrder: "asc" },
    });

    const issues = await prisma.issue.findMany({
      where: { node: { projectId: id } },
      include: { node: { select: { name: true } } },
    });

    const totalBudget = Number(project.totalBudget);
    const totalCost = nodes.reduce((s, n) => s + (Number(n.expectedCost) || 0), 0);
    const totalPaid = nodes.flatMap((n) => n.milestones).filter((m) => m.status === "PAID").reduce((s, m) => s + Number(m.amount), 0);
    const remaining = totalCost - totalPaid;

    if (format === "csv") {
      return generateCsv(project, nodes, totalBudget, totalCost, totalPaid, remaining, lang, et);
    } else if (format === "whatsapp") {
      return generateWhatsApp(project, nodes, issues, totalBudget, totalCost, totalPaid, remaining, lang, et);
    } else if (format === "html") {
      return generateHtml(project, nodes, issues, totalBudget, totalCost, totalPaid, remaining, lang, et);
    } else if (format === "infographic") {
      return generateInfographic(project, nodes, totalBudget, totalCost, totalPaid, remaining, lang, et);
    }

    return new Response("Invalid format", { status: 400 });
  } catch (err) {
    return handleError(err);
  }
}

/* ───────────────── CSV ───────────────── */

function generateCsv(project: any, nodes: any[], budget: number, cost: number, paid: number, remaining: number, lang: Lang, et: (k: string) => string) {
  const rows: string[][] = [];

  rows.push([et("projectReport"), project.name]);
  rows.push([et("generated"), fmtDate(new Date(), lang)]);
  rows.push([et("budget"), String(budget), et("totalCost"), String(cost), et("paid"), String(paid), et("remaining"), String(remaining)]);
  rows.push([]);

  rows.push([et("task"), et("parent"), et("category"), et("vendor"), et("rooms"), et("status"), et("cost"), et("paid"), et("remaining"), "%"]);

  for (const n of nodes) {
    const nodePaid = n.milestones.filter((m: any) => m.status === "PAID").reduce((s: number, m: any) => s + Number(m.amount), 0);
    const nodeCost = Number(n.expectedCost || 0);
    const nodeRemaining = nodeCost - nodePaid;
    const pct = nodeCost > 0 ? Math.round((nodePaid / nodeCost) * 100) : 0;
    const rooms = n.rooms.map((r: any) => r.room.name).join(", ");

    rows.push([
      n.name,
      n.parent?.name || "",
      n.category?.name || "",
      n.vendor?.name || "",
      rooms,
      n.status,
      String(nodeCost || ""),
      String(nodePaid || ""),
      String(nodeRemaining || ""),
      nodeCost > 0 ? `${pct}%` : "",
    ]);
  }

  rows.push([]);
  rows.push([et("payments")]);
  rows.push([et("task"), et("milestone"), et("amount"), et("status"), et("dueDate"), et("paidDate")]);

  for (const n of nodes) {
    for (const m of n.milestones) {
      rows.push([
        n.name,
        m.label,
        String(Number(m.amount)),
        m.status,
        m.dueDate ? fmtDate(m.dueDate, lang) : "",
        m.paidDate ? fmtDate(m.paidDate, lang) : "",
      ]);
    }
  }

  const csv = rows.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")).join("\n");

  return new Response(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${project.name.replace(/[^a-zA-Z0-9\u0590-\u05FF ]/g, "_")}_report.csv"`,
    },
  });
}

/* ───────────────── WhatsApp ───────────────── */

function generateWhatsApp(project: any, nodes: any[], issues: any[], budget: number, cost: number, paid: number, remaining: number, lang: Lang, et: (k: string) => string) {
  const pct = cost > 0 ? Math.round((paid / cost) * 100) : 0;
  const openIssues = issues.filter((i) => i.status !== "RESOLVED");

  let text = `🏗️ *${project.name}*\n`;
  text += `📅 ${fmtDate(new Date(), lang)}\n\n`;

  text += `💰 *${et("budget")}:* ${fmtILS(budget)}\n`;
  text += `📊 *${et("totalCost")}:* ${fmtILS(cost)}\n`;
  text += `✅ *${et("paid")}:* ${fmtILS(paid)} (${pct}%)\n`;
  text += `⏳ *${et("remaining")}:* ${fmtILS(remaining)}\n`;
  text += `🏦 *${et("budgetLeft")}:* ${fmtILS(budget - cost)}\n\n`;

  const completedNodes = nodes.filter((n) => n.status === "COMPLETED");
  const inProgressNodes = nodes.filter((n) => n.status === "IN_PROGRESS");
  const pendingNodes = nodes.filter((n) => !["COMPLETED", "IN_PROGRESS", "CANCELLED"].includes(n.status));

  if (inProgressNodes.length > 0) {
    text += `🔨 *${et("inProgress")} (${inProgressNodes.length}):*\n`;
    for (const n of inProgressNodes.slice(0, 10)) {
      const nc = Number(n.expectedCost || 0);
      text += `  • ${n.name}${nc ? ` — ${fmtILS(nc)}` : ""}${n.vendor?.name ? ` (${n.vendor.name})` : ""}\n`;
    }
    if (inProgressNodes.length > 10) text += `  ... +${inProgressNodes.length - 10} more\n`;
    text += "\n";
  }

  if (pendingNodes.length > 0) {
    text += `📋 *${et("pending")} (${pendingNodes.length}):*\n`;
    for (const n of pendingNodes.slice(0, 10)) {
      const nc = Number(n.expectedCost || 0);
      text += `  • ${n.name}${nc ? ` — ${fmtILS(nc)}` : ""}\n`;
    }
    if (pendingNodes.length > 10) text += `  ... +${pendingNodes.length - 10} more\n`;
    text += "\n";
  }

  if (completedNodes.length > 0) {
    text += `✅ *${et("completed")} (${completedNodes.length}):*\n`;
    for (const n of completedNodes.slice(0, 5)) {
      text += `  • ${n.name}\n`;
    }
    if (completedNodes.length > 5) text += `  ... +${completedNodes.length - 5} more\n`;
    text += "\n";
  }

  if (openIssues.length > 0) {
    text += `⚠️ *${et("issues")} (${openIssues.length}):*\n`;
    for (const i of openIssues.slice(0, 5)) {
      text += `  • ${i.title}${i.node?.name ? ` — ${i.node.name}` : ""}\n`;
    }
    text += "\n";
  }

  const upcoming = nodes
    .flatMap((n) => n.milestones.filter((m: any) => m.status !== "PAID" && m.dueDate).map((m: any) => ({ ...m, taskName: n.name })))
    .sort((a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime())
    .slice(0, 5);

  if (upcoming.length > 0) {
    text += `📆 *${et("payments")}:*\n`;
    for (const m of upcoming) {
      text += `  • ${m.label} (${m.taskName}) — ${fmtILS(Number(m.amount))} — ${fmtDate(m.dueDate, lang)}\n`;
    }
  }

  return Response.json({ text, shareUrl: `https://wa.me/?text=${encodeURIComponent(text)}` });
}

/* ───────────────── HTML ───────────────── */

function generateHtml(project: any, nodes: any[], issues: any[], budget: number, cost: number, paid: number, remaining: number, lang: Lang, et: (k: string) => string) {
  const pct = cost > 0 ? Math.round((paid / cost) * 100) : 0;
  const openIssues = issues.filter((i) => i.status !== "RESOLVED");
  const dir = lang === "he" ? "rtl" : "ltr";

  let html = `<!DOCTYPE html><html dir="${dir}" lang="${lang}"><head><meta charset="utf-8">
<title>${project.name} — ${et("projectReport")}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1A1714; }
  h1 { color: #B8956A; border-bottom: 3px solid #B8956A; padding-bottom: 12px; }
  h2 { color: #6B6460; margin-top: 30px; }
  .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 16px; margin: 20px 0; }
  .stat { background: #F5F2EE; border-radius: 12px; padding: 16px; text-align: center; }
  .stat-value { font-size: 24px; font-weight: 700; color: #1A1714; }
  .stat-label { font-size: 12px; color: #6B6460; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }
  th { background: #1A1714; color: #F5F2EE; padding: 10px 12px; text-align: start; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; }
  td { padding: 8px 12px; border-bottom: 1px solid #E8E3DD; }
  tr:hover td { background: rgba(184,149,106,0.06); }
  .paid { color: #5E8A66; font-weight: 600; }
  .remaining { color: #C4614A; font-weight: 600; }
  .status { display: inline-block; padding: 2px 8px; border-radius: 6px; font-size: 10px; font-weight: 700; }
  .COMPLETED { background: #5E8A6615; color: #5E8A66; }
  .IN_PROGRESS { background: #B8956A1A; color: #B8956A; }
  .PENDING, .NOT_STARTED { background: #E8E3DD; color: #6B6460; }
  .CANCELLED { background: #C4614A12; color: #C4614A; }
  .progress { height: 8px; background: #E8E3DD; border-radius: 4px; overflow: hidden; margin-top: 8px; }
  .progress-fill { height: 100%; background: linear-gradient(90deg, #5E8A66, #78B080); border-radius: 4px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #E8E3DD; font-size: 11px; color: #A39E99; }
</style></head><body>
<h1>${project.name}</h1>
<p style="color:#A39E99">${et("generated")} ${fmtDate(new Date(), lang)} · Reno Tracker</p>

<div class="stats">
  <div class="stat"><div class="stat-value">${fmtILS(budget)}</div><div class="stat-label">${et("budget")}</div></div>
  <div class="stat"><div class="stat-value">${fmtILS(cost)}</div><div class="stat-label">${et("totalCost")}</div></div>
  <div class="stat"><div class="stat-value" style="color:#5E8A66">${fmtILS(paid)}</div><div class="stat-label">${et("paid")} (${pct}%)</div></div>
  <div class="stat"><div class="stat-value" style="color:#C4614A">${fmtILS(remaining)}</div><div class="stat-label">${et("remaining")}</div></div>
  <div class="stat"><div class="stat-value" style="color:${budget - cost >= 0 ? '#5E8A66' : '#C4614A'}">${fmtILS(budget - cost)}</div><div class="stat-label">${et("budgetLeft")}</div></div>
</div>
<div class="progress"><div class="progress-fill" style="width:${Math.min(pct, 100)}%"></div></div>

<h2>${et("task")} (${nodes.length})</h2>
<table>
<tr><th>${et("task")}</th><th>${et("parent")}</th><th>${et("category")}</th><th>${et("vendor")}</th><th>${et("rooms")}</th><th>${et("status")}</th><th>${et("cost")}</th><th>${et("paid")}</th><th>${et("left")}</th></tr>`;

  for (const n of nodes) {
    const nc = Number(n.expectedCost || 0);
    const np = n.milestones.filter((m: any) => m.status === "PAID").reduce((s: number, m: any) => s + Number(m.amount), 0);
    const nr = nc - np;
    const rooms = n.rooms.map((r: any) => r.room.name).join(", ");
    html += `<tr>
  <td><strong>${n.name}</strong></td>
  <td>${n.parent?.name || "—"}</td>
  <td>${n.category?.name || "—"}</td>
  <td>${n.vendor?.name || "—"}</td>
  <td>${rooms || "—"}</td>
  <td><span class="status ${n.status}">${n.status.replace(/_/g, " ")}</span></td>
  <td>${nc ? fmtILS(nc) : "—"}</td>
  <td class="paid">${np ? fmtILS(np) : "—"}</td>
  <td class="remaining">${nr > 0 ? fmtILS(nr) : "—"}</td>
</tr>`;
  }

  html += `</table>`;

  const allMs = nodes.flatMap((n) => n.milestones.map((m: any) => ({ ...m, taskName: n.name })));
  if (allMs.length > 0) {
    html += `<h2>${et("payments")} (${allMs.length})</h2><table>
<tr><th>${et("task")}</th><th>${et("milestone")}</th><th>${et("amount")}</th><th>${et("status")}</th><th>${et("dueDate")}</th><th>${et("paidDate")}</th></tr>`;
    for (const m of allMs) {
      html += `<tr>
  <td>${m.taskName}</td><td>${m.label}</td>
  <td>${fmtILS(Number(m.amount))}</td>
  <td><span class="status ${m.status}">${m.status}</span></td>
  <td>${m.dueDate ? fmtDate(m.dueDate, lang) : "—"}</td>
  <td>${m.paidDate ? fmtDate(m.paidDate, lang) : "—"}</td>
</tr>`;
    }
    html += `</table>`;
  }

  if (openIssues.length > 0) {
    html += `<h2>${et("issues")} (${openIssues.length})</h2><table>
<tr><th>${et("issues")}</th><th>${et("task")}</th><th>${et("status")}</th></tr>`;
    for (const i of openIssues) {
      html += `<tr><td>${i.title}</td><td>${i.node?.name || "—"}</td><td><span class="status ${i.status}">${i.status.replace(/_/g, " ")}</span></td></tr>`;
    }
    html += `</table>`;
  }

  html += `<div class="footer">${et("generatedBy")} · ${new Date().toISOString()}</div></body></html>`;

  return new Response(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `attachment; filename="${project.name.replace(/[^a-zA-Z0-9\u0590-\u05FF ]/g, "_")}_report.html"`,
    },
  });
}

/* ───────────────── Infographic (SVG 1200x630) ───────────────── */

function generateInfographic(project: any, nodes: any[], budget: number, cost: number, paid: number, remaining: number, lang: Lang, et: (k: string) => string) {
  const pct = cost > 0 ? Math.round((paid / cost) * 100) : 0;
  const budgetLeft = budget - cost;
  const isRtl = lang === "he";

  // Milestoned amounts
  const milestoned = nodes.flatMap((n) => n.milestones).reduce((s: number, m: any) => s + Number(m.amount), 0);
  const pendingAmount = Math.max(milestoned - paid, 0);

  // Status counts
  const completedCount = nodes.filter((n) => n.status === "COMPLETED").length;
  const inProgressCount = nodes.filter((n) => n.status === "IN_PROGRESS").length;
  const pendingCount = nodes.filter((n) => !["COMPLETED", "IN_PROGRESS", "CANCELLED"].includes(n.status)).length;

  // Top 5 costliest tasks
  const topTasks = [...nodes].filter((n) => n.expectedCost).sort((a, b) => Number(b.expectedCost) - Number(a.expectedCost)).slice(0, 5);

  const date = fmtDate(new Date(), lang);
  const statusLabel = budgetLeft >= 0 ? et("onTrack") : et("overBudget");
  const statusColor = budgetLeft >= 0 ? "#5E8A66" : "#C4614A";

  // ── Progress bar segments (stacked, 3-color) ──
  const barX = 60;
  const barY = 260;
  const barW = 1080;
  const barH = 14;
  const barTotal = Math.max(cost, 1);
  const paidW = Math.round(barW * (paid / barTotal));
  const pendingW = Math.round(barW * (pendingAmount / barTotal));
  const remainingW = barW - paidW - pendingW;

  // ── Stat cards ──
  const cardW = 240;
  const cardH = 90;
  const cardY = 140;
  const cardGap = 30;
  const cardsStartX = 60;

  interface CardDef { label: string; value: string; color: string }
  const cards: CardDef[] = [
    { label: et("budget"), value: fmtILS(budget), color: "#1A1714" },
    { label: et("paid"), value: fmtILS(paid), color: "#5E8A66" },
    { label: et("remaining"), value: fmtILS(remaining), color: "#C4614A" },
    { label: `${pct}%`, value: statusLabel, color: statusColor },
  ];

  let cardsSvg = "";
  for (let i = 0; i < cards.length; i++) {
    const card = cards[i];
    const cx = isRtl
      ? 1200 - cardsStartX - cardW - i * (cardW + cardGap)
      : cardsStartX + i * (cardW + cardGap);
    const anchor = isRtl ? "end" : "start";
    const tx = isRtl ? cx + cardW - 20 : cx + 20;

    cardsSvg += `<rect x="${cx}" y="${cardY}" width="${cardW}" height="${cardH}" rx="12" fill="white" filter="url(#cardShadow)"/>`;
    cardsSvg += `<text x="${tx}" y="${cardY + 32}" font-size="12" fill="#6B6460" font-family="system-ui" text-anchor="${anchor}">${card.label}</text>`;
    cardsSvg += `<text x="${tx}" y="${cardY + 64}" font-size="24" font-weight="700" fill="${card.color}" font-family="system-ui" text-anchor="${anchor}">${card.value}</text>`;
  }

  // ── Stacked progress bar ──
  const progressBarSvg = `
    <rect x="${barX}" y="${barY}" width="${barW}" height="${barH}" rx="7" fill="#E8E3DD"/>
    <rect x="${barX}" y="${barY}" width="${paidW + pendingW}" height="${barH}" rx="7" fill="#B8956A"/>
    <rect x="${barX}" y="${barY}" width="${paidW}" height="${barH}" rx="7" fill="#5E8A66"/>`;

  // ── Status summary line ──
  const summaryY = barY + 36;
  const summaryAnchor = isRtl ? "end" : "start";
  const summaryX = isRtl ? 1140 : 60;
  const summaryText = `${completedCount} ${et("completed")} · ${inProgressCount} ${et("inProgress")} · ${pendingCount} ${et("pending")}`;

  // ── Top tasks with mini progress bars ──
  const tasksStartY = 340;
  const taskColX = isRtl ? 1140 : 60;
  const taskBarStartX = isRtl ? 100 : 380;
  const taskBarW = 400;
  const taskAnchor = isRtl ? "end" : "start";
  const taskValueAnchor = isRtl ? "start" : "end";
  const taskValueX = isRtl ? 60 : 1140;

  let tasksSvg = "";
  const topTasksLabel = et("topTasks").toUpperCase();
  const topLabelX = isRtl ? 1140 : 60;
  tasksSvg += `<text x="${topLabelX}" y="${tasksStartY - 10}" font-size="11" font-weight="700" fill="#B8956A" font-family="system-ui" letter-spacing="1.5" text-anchor="${taskAnchor}">${topTasksLabel}</text>`;

  for (let i = 0; i < topTasks.length; i++) {
    const t = topTasks[i];
    const ty = tasksStartY + i * 44;
    const nc = Number(t.expectedCost);
    const np = t.milestones.filter((m: any) => m.status === "PAID").reduce((s: number, m: any) => s + Number(m.amount), 0);
    const tpct = nc > 0 ? Math.round((np / nc) * 100) : 0;
    const fillW = Math.round(taskBarW * (tpct / 100));

    // Task name
    tasksSvg += `<text x="${taskColX}" y="${ty + 14}" font-size="13" fill="#1A1714" font-family="system-ui" font-weight="600" text-anchor="${taskAnchor}">${t.name.slice(0, 28)}</text>`;

    // Mini progress bar
    if (isRtl) {
      const barRightEdge = taskBarStartX + taskBarW;
      tasksSvg += `<rect x="${taskBarStartX}" y="${ty + 22}" width="${taskBarW}" height="6" rx="3" fill="#E8E3DD"/>`;
      tasksSvg += `<rect x="${barRightEdge - fillW}" y="${ty + 22}" width="${fillW}" height="6" rx="3" fill="#5E8A66"/>`;
    } else {
      tasksSvg += `<rect x="${taskBarStartX}" y="${ty + 22}" width="${taskBarW}" height="6" rx="3" fill="#E8E3DD"/>`;
      tasksSvg += `<rect x="${taskBarStartX}" y="${ty + 22}" width="${fillW}" height="6" rx="3" fill="#5E8A66"/>`;
    }

    // Value label
    tasksSvg += `<text x="${taskValueX}" y="${ty + 14}" font-size="11" fill="#6B6460" font-family="system-ui" text-anchor="${taskValueAnchor}">${fmtILS(np)} / ${fmtILS(nc)} (${tpct}%)</text>`;
  }

  // ── Header ──
  const logoX = isRtl ? 1140 : 60;
  const headerAnchor = isRtl ? "end" : "start";
  const dateX = isRtl ? 60 : 1140;
  const dateAnchor = isRtl ? "start" : "end";

  // ── Footer ──
  const footerLeftX = isRtl ? 1140 : 60;
  const footerRightX = isRtl ? 60 : 1140;
  const footerLeftAnchor = isRtl ? "end" : "start";
  const footerRightAnchor = isRtl ? "start" : "end";

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <defs>
    <filter id="cardShadow" x="-4%" y="-4%" width="108%" height="116%">
      <feDropShadow dx="0" dy="2" stdDeviation="6" flood-color="#1A1714" flood-opacity="0.06"/>
    </filter>
  </defs>

  <!-- Background -->
  <rect width="1200" height="630" fill="#F5F2EE" rx="16"/>

  <!-- Header -->
  <rect x="${logoX - (isRtl ? 28 : 0)}" y="36" width="24" height="24" rx="4" fill="#B8956A"/>
  <text x="${isRtl ? logoX - 36 : logoX + 32}" y="56" font-size="26" font-weight="700" fill="#1A1714" font-family="system-ui" text-anchor="${headerAnchor}">${project.name}</text>
  <text x="${isRtl ? logoX - 36 : logoX + 32}" y="78" font-size="12" fill="#A39E99" font-family="system-ui" text-anchor="${headerAnchor}">${et("projectReport")}</text>
  <text x="${dateX}" y="56" font-size="12" fill="#A39E99" font-family="system-ui" text-anchor="${dateAnchor}">${date}</text>

  <!-- Stat cards -->
  ${cardsSvg}

  <!-- Stacked progress bar -->
  ${progressBarSvg}

  <!-- Status summary -->
  <text x="${summaryX}" y="${summaryY}" font-size="12" fill="#6B6460" font-family="system-ui" text-anchor="${summaryAnchor}">${summaryText}</text>

  <!-- Top tasks -->
  ${tasksSvg}

  <!-- Footer -->
  <line x1="60" y1="596" x2="1140" y2="596" stroke="#E8E3DD" stroke-width="1"/>
  <text x="${footerLeftX}" y="618" font-size="10" fill="#A39E99" font-family="system-ui" text-anchor="${footerLeftAnchor}">── ${et("generatedBy")} ──</text>
  <text x="${footerRightX}" y="618" font-size="10" fill="#A39E99" font-family="system-ui" text-anchor="${footerRightAnchor}">── ${date} ──</text>
</svg>`;

  return new Response(svg, {
    headers: { "Content-Type": "image/svg+xml", "Cache-Control": "no-cache" },
  });
}
