import { google, docs_v1 } from "googleapis";
import { prisma } from "@/lib/prisma";
import { requireUser, requireProjectAccess } from "@/lib/dal";
import { handleError } from "@/lib/api";
import { getGoogleAuth } from "@/lib/google-api";

/* ───────────────── Translation dictionary ───────────────── */

const exportDict: Record<string, { en: string; he: string }> = {
  budget: { en: "Budget", he: "תקציב" },
  totalCost: { en: "Total Cost", he: "עלות כוללת" },
  paid: { en: "Paid", he: "שולם" },
  remaining: { en: "Remaining", he: "נותר" },
  budgetLeft: { en: "Budget Left", he: "תקציב שנותר" },
  task: { en: "Task", he: "משימה" },
  parent: { en: "Parent", he: "משימת אב" },
  status: { en: "Status", he: "סטטוס" },
  cost: { en: "Cost", he: "עלות" },
  payments: { en: "Payments", he: "תשלומים" },
  milestone: { en: "Milestone", he: "תשלום" },
  amount: { en: "Amount", he: "סכום" },
  dueDate: { en: "Due Date", he: "תאריך יעד" },
  paidDate: { en: "Paid Date", he: "תאריך תשלום" },
  issues: { en: "Issues", he: "תקלות" },
  financialSummary: { en: "Financial Summary", he: "סיכום פיננסי" },
  progress: { en: "Progress", he: "התקדמות" },
  tasksByParent: { en: "Tasks by Parent", he: "משימות לפי משימת אב" },
  standaloneTasksLabel: { en: "Standalone Tasks", he: "משימות עצמאיות" },
  projectReport: { en: "Project Report", he: "דוח פרויקט" },
  generated: { en: "Generated", he: "נוצר" },
  generatedBy: { en: "Generated by Reno Tracker", he: "נוצר על ידי Reno Tracker" },
  openIssues: { en: "Open Issues", he: "תקלות פתוחות" },
};

type Lang = "en" | "he";

function et(key: string, lang: Lang) {
  return exportDict[key]?.[lang] || key;
}

function fmtILS(n: number) {
  return new Intl.NumberFormat("he-IL", { style: "currency", currency: "ILS", maximumFractionDigits: 0 }).format(n);
}

function fmtDate(d: Date | string, lang: Lang) {
  const locale = lang === "he" ? "he-IL" : "en-IL";
  return new Date(d).toLocaleDateString(locale);
}

/* ───────────────── Helper: build progress bar text ───────────────── */

function progressBar(pct: number): string {
  const filled = Math.round(pct / 5);
  const empty = 20 - filled;
  return "\u2588".repeat(filled) + "\u2591".repeat(empty) + ` ${pct}%`;
}

/* ───────────────── GET handler ───────────────── */

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { userId } = await requireUser();
    const { id } = await params;
    await requireProjectAccess(userId, id);

    const { searchParams } = new URL(request.url);
    const lang: Lang = searchParams.get("lang") === "he" ? "he" : "en";

    const project = await prisma.project.findUnique({ where: { id } });
    if (!project) return new Response("Not found", { status: 404 });

    const nodes = await prisma.projectNode.findMany({
      where: { projectId: id },
      include: {
        vendor: { select: { name: true } },
        category: { select: { name: true } },
        milestones: { select: { label: true, amount: true, status: true, dueDate: true, paidDate: true } },
        rooms: { include: { room: { select: { name: true } } } },
        parent: { select: { name: true } },
      },
      orderBy: { sortOrder: "asc" },
    });

    const issues = await prisma.issue.findMany({
      where: { node: { projectId: id } },
      include: { node: { select: { name: true } } },
    });

    const totalBudget = Number(project.totalBudget);
    const totalCost = nodes.reduce((s, n) => s + (Number(n.expectedCost) || 0), 0);
    const totalPaid = nodes.flatMap((n) => n.milestones).filter((m) => m.status === "PAID").reduce((s, m) => s + Number(m.amount), 0);
    const remaining = totalCost - totalPaid;
    const budgetLeft = totalBudget - totalCost;
    const pct = totalCost > 0 ? Math.round((totalPaid / totalCost) * 100) : 0;

    // ── Get Google auth ──
    let auth;
    try {
      auth = await getGoogleAuth(userId);
    } catch {
      return Response.json(
        { error: "google_auth_required", message: "Please sign out and sign in again to grant Google Docs access." },
        { status: 401 }
      );
    }

    const docs = google.docs({ version: "v1", auth });
    const date = fmtDate(new Date(), lang);
    const title = `${project.name} — ${et("projectReport", lang)} ${date}`;

    // ── Create document ──
    const doc = await docs.documents.create({
      requestBody: { title },
    });

    const documentId = doc.data.documentId!;

    // ── Build requests array (insert from bottom up so indices don't shift) ──
    // We'll build the document content as a series of insertText and formatting requests.
    // Strategy: insert text sequentially, then apply formatting.

    const requests: docs_v1.Schema$Request[] = [];
    let idx = 1; // cursor position (doc starts at index 1)

    // Helper: insert text and advance cursor
    function insertText(text: string): { start: number; end: number } {
      const start = idx;
      requests.push({ insertText: { location: { index: idx }, text } });
      idx += text.length;
      return { start, end: idx };
    }

    // Helper: apply paragraph style
    function applyHeading(start: number, end: number, heading: string) {
      requests.push({
        updateParagraphStyle: {
          range: { startIndex: start, endIndex: end },
          paragraphStyle: { namedStyleType: heading },
          fields: "namedStyleType",
        },
      });
    }

    // Helper: bold text range
    function applyBold(start: number, end: number) {
      requests.push({
        updateTextStyle: {
          range: { startIndex: start, endIndex: end },
          textStyle: { bold: true },
          fields: "bold",
        },
      });
    }

    // Helper: set text color
    function applyColor(start: number, end: number, r: number, g: number, b: number) {
      requests.push({
        updateTextStyle: {
          range: { startIndex: start, endIndex: end },
          textStyle: { foregroundColor: { color: { rgbColor: { red: r, green: g, blue: b } } } },
          fields: "foregroundColor",
        },
      });
    }

    // Helper: set font size
    function applyFontSize(start: number, end: number, size: number) {
      requests.push({
        updateTextStyle: {
          range: { startIndex: start, endIndex: end },
          textStyle: { fontSize: { magnitude: size, unit: "PT" } },
          fields: "fontSize",
        },
      });
    }

    // ── Title ──
    const titleRange = insertText(`${project.name}\n`);
    applyHeading(titleRange.start, titleRange.end, "HEADING_1");

    // ── Date line ──
    const dateRange = insertText(`${et("generated", lang)}: ${date}\n\n`);
    applyColor(dateRange.start, dateRange.end - 1, 0.64, 0.62, 0.6);
    applyFontSize(dateRange.start, dateRange.end - 1, 10);

    // ── Financial Summary heading ──
    const finHeading = insertText(`${et("financialSummary", lang)}\n`);
    applyHeading(finHeading.start, finHeading.end, "HEADING_2");

    // ── Financial summary table ──
    const finTableRows = 2;
    const finTableCols = 5;
    requests.push({
      insertTable: {
        rows: finTableRows,
        columns: finTableCols,
        location: { index: idx },
      },
    });
    // Table takes up: 2 + (rows * (1 + cols * 2)) characters approximately
    // Exact sizing: table start=1, each row start=1, each cell start=1 + end=1, cell content, row end
    // We need to find the end of table. Simpler: calculate based on Google Docs table structure.
    // A table with R rows and C cols at index I occupies:
    //   1 (table start) + R * (1 (row start) + C * (2 (cell start+end) + 1 (newline in cell))) + 1 (table end) - 1
    // = 1 + R * (1 + C * 3) + 0 = 1 + R * (1 + 3C)
    const tableSize = 1 + finTableRows * (1 + finTableCols * 3);
    idx += tableSize;

    // We need to populate the table cells. The table starts at a known index.
    // For a 2x5 table at position P:
    // Cell(0,0) content starts at P + 4
    // Each cell adds 3 to the offset (start marker, newline, end marker)
    // Row adds 1 for row start marker
    // The pattern for cell(r,c): P + 1 (table) + r*(1 + cols*3) + 1 (row) + c*3 + 1 (cell) + 1 (cell content after \n? no)
    // Actually: P+2 for first cell content, then +3 for each subsequent cell in row,
    //           +1 more for row boundary
    // Let me use a simpler approach - we know the table index, let's calculate:
    const tableStart = idx - tableSize;
    // Cell positions in a Google Docs table:
    // table_start + 1 (TABLE_START) + 1 (ROW_START) + 1 (CELL_START) + 1 (PARAGRAPH_START) = content of cell(0,0)
    // After cell content: +1 (PARAGRAPH_END) + 1 (CELL_END) + 1 (CELL_START) + 1 (PARAGRAPH_START) = next cell
    // So cell stride is content_length + 2 (para end + cell end) + 2 (cell start + para start)
    // For empty cells (just \n), each cell occupies 3 indices: CELL_START, \n (paragraph), CELL_END
    // Row occupies: ROW_START + cols * 3
    // First cell content at: tableStart + 1 + 1 + 1 + 1 = tableStart + 4
    // But since all cells are empty with just \n, cell(r,c) content = tableStart + 1 + 1 + r*(1 + cols*3) + c*3 + 1 + 1
    //   Simplified: tableStart + 4 + r*(1 + cols*3) + c*3

    // Actually Google Docs table indices are complex. Let's use a different approach:
    // Insert a newline after table and use batchUpdate to populate later.
    // Better approach: don't use insertTable, just use formatted text.

    // Let me restart with a simpler text-based approach that's more reliable.

    // Reset - we'll rebuild without tables, using formatted text lines instead.
    // This avoids the complex table index math.

    // Clear requests and start over with a pure text approach
    requests.length = 0;
    idx = 1;

    // ── Title ──
    const titleR = insertText(`${project.name}\n`);
    applyHeading(titleR.start, titleR.end, "HEADING_1");

    // ── Date ──
    const dateR = insertText(`${et("generated", lang)}: ${date}\n\n`);
    applyColor(dateR.start, dateR.end - 1, 0.64, 0.62, 0.6);

    // ── Financial Summary ──
    const finH = insertText(`${et("financialSummary", lang)}\n`);
    applyHeading(finH.start, finH.end, "HEADING_2");

    const finLines = [
      `${et("budget", lang)}:  ${fmtILS(totalBudget)}`,
      `${et("totalCost", lang)}:  ${fmtILS(totalCost)}`,
      `${et("paid", lang)}:  ${fmtILS(totalPaid)}`,
      `${et("remaining", lang)}:  ${fmtILS(remaining)}`,
      `${et("budgetLeft", lang)}:  ${fmtILS(budgetLeft)}`,
    ];
    for (const line of finLines) {
      const r = insertText(`${line}\n`);
      // Bold the label part (before the colon)
      const colonIdx = line.indexOf(":");
      if (colonIdx > 0) {
        applyBold(r.start, r.start + colonIdx);
      }
    }

    // ── Progress bar ──
    insertText("\n");
    const progH = insertText(`${et("progress", lang)}\n`);
    applyHeading(progH.start, progH.end, "HEADING_2");
    const progText = progressBar(pct);
    const progR = insertText(`${progText}\n\n`);
    applyFontSize(progR.start, progR.start + progText.length, 14);
    // Color the filled blocks green
    const filledCount = Math.round(pct / 5);
    if (filledCount > 0) {
      applyColor(progR.start, progR.start + filledCount, 0.37, 0.54, 0.4); // green
    }

    // ── Tasks by parent ──
    const taskH = insertText(`${et("tasksByParent", lang)}\n`);
    applyHeading(taskH.start, taskH.end, "HEADING_2");

    // Group by parent
    const byParent = new Map<string, typeof nodes>();
    for (const n of nodes) {
      const parentName = n.parent?.name || et("standaloneTasksLabel", lang);
      if (!byParent.has(parentName)) byParent.set(parentName, []);
      byParent.get(parentName)!.push(n);
    }

    for (const [parentName, children] of byParent) {
      const parentR = insertText(`${parentName}\n`);
      applyHeading(parentR.start, parentR.end, "HEADING_3");

      for (const n of children) {
        const nc = Number(n.expectedCost || 0);
        const np = n.milestones.filter((m) => m.status === "PAID").reduce((s, m) => s + Number(m.amount), 0);
        const line = `${n.name}  |  ${et("status", lang)}: ${n.status.replace(/_/g, " ")}  |  ${et("cost", lang)}: ${nc ? fmtILS(nc) : "—"}  |  ${et("paid", lang)}: ${np ? fmtILS(np) : "—"}`;
        const lineR = insertText(`${line}\n`);
        // Bold task name
        applyBold(lineR.start, lineR.start + n.name.length);
      }
      insertText("\n");
    }

    // ── Payment milestones ──
    const allMs = nodes.flatMap((n) => n.milestones.map((m) => ({ ...m, taskName: n.name })));
    if (allMs.length > 0) {
      const payH = insertText(`${et("payments", lang)}\n`);
      applyHeading(payH.start, payH.end, "HEADING_2");

      // Header line
      const headerLine = `${et("task", lang)}  |  ${et("milestone", lang)}  |  ${et("amount", lang)}  |  ${et("status", lang)}  |  ${et("dueDate", lang)}  |  ${et("paidDate", lang)}`;
      const headerR = insertText(`${headerLine}\n`);
      applyBold(headerR.start, headerR.end - 1);

      for (const m of allMs) {
        const mLine = `${m.taskName}  |  ${m.label}  |  ${fmtILS(Number(m.amount))}  |  ${m.status}  |  ${m.dueDate ? fmtDate(m.dueDate, lang) : "—"}  |  ${m.paidDate ? fmtDate(m.paidDate, lang) : "—"}`;
        insertText(`${mLine}\n`);
      }
      insertText("\n");
    }

    // ── Open issues ──
    const openIssues = issues.filter((i) => i.status !== "RESOLVED");
    if (openIssues.length > 0) {
      const issH = insertText(`${et("openIssues", lang)} (${openIssues.length})\n`);
      applyHeading(issH.start, issH.end, "HEADING_2");

      for (const i of openIssues) {
        const issueLine = `- ${i.title}${i.node?.name ? `  (${i.node.name})` : ""}`;
        insertText(`${issueLine}\n`);
      }
      insertText("\n");
    }

    // ── Footer ──
    const footerR = insertText(`${et("generatedBy", lang)}  ·  ${date}\n`);
    applyColor(footerR.start, footerR.end - 1, 0.64, 0.62, 0.6);
    applyFontSize(footerR.start, footerR.end - 1, 9);

    // ── Apply all requests ──
    if (requests.length > 0) {
      await docs.documents.batchUpdate({
        documentId,
        requestBody: { requests },
      });
    }

    const url = `https://docs.google.com/document/d/${documentId}`;
    return Response.json({ url });
  } catch (err) {
    return handleError(err);
  }
}
